openmrs/openmrs-module-locationbasedaccess

- .travis.yml
Adding Travis setup file to the repository.
> Added Travis to the repo

- api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java
The find patients page will list some patients who have the recent encounters and recent search also. This list contains the patients who do not belong to the logged in location of the user. The issue was fixed through this PR, and added advice to track the getPatient method from patientService.
Ticket : https://issues.openmrs.org/browse/LBAC-8
> LBAC-8 Fixed to restrict the patients on findPatients initial view

- omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/ViewUserLocationFragmentController.java
Minor change on the user location object name to the proper name.
> LBAC-2 Added changes to user location object name

- api/pom.xml
- omod/pom.xml
- pom.xml
Added changes for the release 0.1.0-beta of location based access control module
> Prepare for release 0.1.0-beta

- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviser.java
We implemented the LBAC for working tightly with the sessionLocationId. So it failed to work for the user through the REST service since that user will not have the sessionLocationId. So We need to give the priority to,
- First - Get the assigned location from user property (Need update)
- Second - Get the assigned location from session location (already implemented)
Ticekt : https://issues.openmrs.org/browse/LBAC-16
> LBAC-16 Added fix to check for the user property before session id for Encounter Restrictions

- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/LocationSearchAdviser.java
Since the Accessible Location function is already migrated to the LocationUtils, this PR contains the chances to use that function in the LocationSearchAdvicer.
Ticket : https://issues.openmrs.org/browse/LBAC-18
> LBAC-18 Changed to AccessibleLocation function from LocationUtils

- omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/AddLocationFragmentController.java
This PR contains the fix to load the location information from the user in the Mange Account page while editing the user. 
Ticket : https://issues.openmrs.org/browse/LBAC-19
> LBAC-19 Added fix to load the location from the user in Manage Account Fragment

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/PatientSearchAdviserTest.java
- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/common/AOPContextSensitiveTest.java
- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/common/TestWithAOP.java
- api/src/test/resources/include/AdminUserData.xml
- api/src/test/resources/include/PatientTestData.xml
- pom.xml
Added Unit tests for PatientSearchAdviser AOP Implementation. Tested all methods in the Advice. 
Ticket : https://issues.openmrs.org/browse/LBAC-6
> LBAC-6 Added Unit tests for PatientSearchAdviser

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/UserSearchAdviserTest.java
- api/src/test/resources/include/PatientTestData.xml
I've added unit tests for UserSearchAdviser named UserSearchAdviserTest.
In the test I've tested that all admin can access all users from different ways.
I've also given privileges to users as required.
[Issue](https://issues.openmrs.org/browse/LBAC-25)
[Task Instance](https://codein.withgoogle.com/dashboard/task-instances/6320141655605248/)
> LBAC-25: Added Unit tests for UserSearchAdviser

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/PersonSearchAdviserTest.java
I've added unit tests for PersonSearchAdviser Class.
JIRA: <a href="https://issues.openmrs.org/browse/LBAC-24">LBAC-24</a>
GCI: <a href="https://codein.withgoogle.com/dashboard/task-instances/5162956233900032/">Task Instance</a>
> LBAC-24: Adding Unit tests for PersonSearchAdviser Class

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/PersonSearchAdviserTest.java
I did not create a ticket for this because it's a subtle change.
Although I heard that @sviho was battling with the code formatting, the merged code was a mess of spaces and tabs. Some parts of the code looked like if they were "6 space" indentated.
It looked horrible.
So here's a PR. Have a great day :)
> Fixed indents of PersonSearchAdviserTest.java

- .github/PULL_REQUEST_TEMPLATE.md
Proposed a Pull Request Format similar to openmrs-core one.
[see](https://issues.openmrs.org/browse/LBAC-28)
> LBAC-28 Adding a PR template to this repository

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviserTest.java
- api/src/test/resources/include/PatientTestData.xml
I've added unit tests for EncounterSearchAdviser named EncounterSearchAdviserTest.
In the test I've tested that all admin can access all users from different ways.
I've also given privileges to users as required.
[Issue](https://issues.openmrs.org/browse/LBAC-22)
[Task Instance](https://codein.withgoogle.com/dashboard/task-instances/6518619409219584/)
> LBAC-22 Added Unit tests for EncounterSearchAdviser

- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviser.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/LocationSearchAdviser.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/PatientSearchAdviser.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/PersonSearchAdviser.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/UserSearchAdviser.java
I've refactored the `SearchAdviser` classes as it was described in the JIRA ticket below.
see https://issues.openmrs.org/browse/LBAC-29
> LBAC-29: Refactored SearchAdvisers to increase readability and extensibility

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviserTest.java
- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/PatientSearchAdviserTest.java
- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/PersonSearchAdviserTest.java
- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/UserSearchAdviserTest.java
I have corrected the usage of assertEquals to match its format with the conventional one. 
I have also made changes according to [this PR](https://github.com/openmrs/openmrs-module-locationbasedaccess/pull/53) so that there is no conflict while merging.
see https://issues.openmrs.org/browse/LBAC-31
> LBAC-31 Correcting usage of assertEquals

- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/LocationUtilsTest.java
- api/src/test/resources/include/LocationUtilTestData.xml
see https://issues.openmrs.org/browse/LBAC-32
> LBAC-32 Added Tests for LocationUtils

- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessActivator.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessConstants.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/utils/LocationUtils.java
Added personAttributeType to store location with Uuid as `0a93cbc6-5d65-4886-8091-47a25d3df944`.
Used the same UUID as value and added `locationbasedaccess.locationAttributeUuid` named global property to store PersonAttributeType.
see https://issues.openmrs.org/browse/LBAC-20
> LBAC-20: Automation of Deployment steps

- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessConstants.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/EncounterServiceInterceptorAdvice.java
we use a global property to whether restrict on Encounter Location or Patient Location and use it for restrictions.
see https://issues.openmrs.org/browse/LBAC-37
No? -> figure out why and add the fix to your commit. It is your …
> LBAC-37: Encounter Access based on patient Location

- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessActivator.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessConstants.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/EncounterServiceInterceptorAdvice.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/LocationServiceInterceptorAdvice.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/PatientServiceInterceptorAdvice.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/PersonServiceInterceptorAdvice.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/UserServiceInterceptorAdvice.java
- api/src/test/resources/include/LocationTestData.xml
- api/src/test/resources/include/PatientTestData.xml
Added Global property for every entity to customise the Restriction only on few entitites rather than only.
Having global property `locationbasedacess.patientaccess` as `true` implies to have LBAC restriction on it.
see https://issues.openmrs.org/browse/LBAC-38
added all formatting changes to my …
> LBAC-38 : Global Property for Every Entity Restriction

- .travis.yml
see https://issues.openmrs.org/browse/LBAC-45
> LBAC-45 Failure of Travis Build

- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessActivator.java
see https://issues.openmrs.org/browse/LBAC-46
> LBAC-46 :Person Entity Restriction Global property Added

- api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessActivator.java
- api/src/main/java/org/openmrs/module/locationbasedaccess/utils/LocationUtils.java
- api/src/test/java/org/openmrs/module/locationbasedaccess/aop/LocationUtilsTest.java
- api/src/test/resources/include/LocationUtilTestData.xml
Added a function`getUserAccessibleLocationUuidsWithUserPrivileges`  in utils to get accessible Locations for the user. will replace the current function `getUserAccessibleLocationUuid` once LBAC-33 gets merged. Making changes in `getUserAccessibleLocationUuid` we need to make changes in All classes using it and then will make conflicts once LBAC-33.
see https://issues.openmrs.org/browse/LBAC-34
existing code that was well tested you do not …
> LBAC-34: Added UserRole Based Location Access

- omod/pom.xml
- omod/src/main/java/org/openmrs/module/locationbasedaccess/web/controller/LBACOnOffController.java
- omod/src/test/java/org/openmrs/module/locationbasedaccess/web/controller/LBACOnOffController_Test.java
- omod/src/test/resources/GlobalPropertyData.xml
- pom.xml
see https://issues.openmrs.org/browse/LBAC-41
> LBAC-41: LBAC On/Off

- omod/src/main/java/org/openmrs/module/locationbasedaccess/web/controller/LocationWiseEntityCountController.java
see https://issues.openmrs.org/browse/LBAC-44
> LBAC-44: Get Entities Location wise count

- omod/src/main/java/org/openmrs/module/locationbasedaccess/web/controller/PatientsMigrationController.java
- omod/src/test/java/org/openmrs/module/locationbasedaccess/web/controller/PatientsMigrationController_Test.java
- omod/src/test/resources/PatientMigrationData.xml
Added an End-point with /patient-migration a post request with patient's list and location as 
`{
"locationUuid": "2131aff8-2e2a-480a-b7ab-4ac53250262b",  
"patientList": ["c5da9efc-3470-4591-bf20-559e5e79f7e7","661e8829-aae1-4e48-b389-819205acef0b","5ab211f5-f461-4239-b2dc-43a83ea3e595"]
}` 
will migrate patients to that Location.
see https://issues.openmrs.org/browse/LBAC-39 …
> LBAC-39 : MIgration of Patients to a Location

- omod/src/main/java/org/openmrs/module/locationbasedaccess/web/controller/ModuleDependencyController.java
see https://issues.openmrs.org/browse/LBAC-40
> LBAC-40: check and show the required Modules
