api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessActivator.java

There was an minor issue occurred in the [Pull 5 ](https://github.com/openmrs/openmrs-module-locationbasedaccess/pull/5/). It should be fixed to avoid the further build failures.

Minor fix on the module to avoid the build failure

---

api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/field/LocationsFragmentController.java
omod/src/main/resources/config.xml
omod/src/main/resources/webModuleApplicationContext.xml
omod/src/main/webapp/fragments/field/locations.gsp
pom.xml

Added implementation for assigning the users to the locations on registration. 
- PatientControlImpl - Contains the code base to register locations for the persons
- Constants - Included some constants variables for the code usage
Ticekt : https://issues.openmrs.org/browse/LBAC-3

LBAC-3 Added implementation for assigning the patients to the locations on registration

---

api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessConstants.java
api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/field/LocationsFragmentController.java
omod/src/main/resources/apps/editLocation_extension.json
omod/src/main/webapp/fragments/field/locations.gsp

Added Implementation to edit the patient's locations through the patient dashboard
- Added edit link to patient dashboard general actions
Ticket : https://issues.openmrs.org/browse/LBAC-5

LBAC-5 Added implementation to edit the patient's locations though patient dashboard

---

omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/field/LocationsFragmentController.java
pom.xml

Currently, the first item is selected default to the fragment location selector. This PR contains the fix to select the session location as the default location to the location selector in the fragment.
Ticket : https://issues.openmrs.org/browse/LBAC-7

LBAC-7 Added fix to select the session locaion in the location selector

---

api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java

Added AOP Advice to getPatientByUuid() method in the PatientService to restrict by the location property.
Ticket : https://issues.openmrs.org/browse/LBAC-9

LBAC-9 Added AOP Advice to getPatientByUuid method in the PatientService

---

api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java

Added exception for Daemon thread to access the methods which are covered by AOP Advices in Location based access control. Then the daemon thread user will not have any restrictions to access the objects from different locations.
Ticket : https://issues.openmrs.org/browse/LBAC-10

LBAC-10 Added exception for Daemon thread user to access the methods covered with AOP Advices

---

api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java

Since the System Administrator should have access to all the data in the system, Location Based Access control module should give an exception to see all the patients. This PR contains the changes to allow the system administrator to access all patients in the system.
Ticket : https://issues.openmrs.org/browse/LBAC-11

LBAC-11 Added fix to allow system administrator to access all patients

---

api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/PatientHeaderLocationFragmentController.java
omod/src/main/resources/apps/patientHeader_extension.json
omod/src/main/webapp/fragments/patientHeaderLocation.gsp

This PR contains the implementation to show the patient location in the patient dashboard if the logged in user is System Administrator.
Ticket : https://issues.openmrs.org/browse/LBAC-12

LBAC-12 Added fix to show the patient location in the patient dashboard

---

api/src/main/java/org/openmrs/module/locationbasedaccess/PatientSearchAdviser.java

Added fix to check the NPE for Context.getAuthenticatedUser()
Ticket : https://issues.openmrs.org/browse/LBAC-10

LBAC-10 Added fix to check the NPE for getAuthenticatedUser()

---

api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessConstants.java
api/src/main/java/org/openmrs/module/locationbasedaccess/LocationUtils.java
api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/AddLocationFragmentController.java
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/ViewUserLocationFragmentController.java
omod/src/main/resources/apps/createUser_extension.json
omod/src/main/webapp/fragments/manageAccount/addLocation.gsp
omod/src/main/webapp/fragments/manageAccount/viewUserLocation.gsp

This PR contains the implementation to assign the location to the users on registration. It contains two custom fragments for,
- Add/Edit the location in the user dashboard
- View the location information in the user dashboard
Ticket : https://issues.openmrs.org/browse/LBAC-2

LBAC-2 Added implementation to add the locations to the users on registration

---

api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessActivator.java
api/src/main/java/org/openmrs/module/locationbasedaccess/LocationBasedAccessConstants.java

This PR contains the implementation to create the refapp location global propery while starting the module.
Ticekt : https://issues.openmrs.org/browse/LBAC-13

LBAC-13 Added implementation to create RefApp location glopal property

---

api/src/main/java/org/openmrs/module/locationbasedaccess/EncounterSearchAdviser.java
omod/src/main/resources/config.xml

- Added the restrictions to these following methods from the EncounterService class which is directly getting the Encounter object from the DAO.    It can restrict by the encounters from other locations.
1. getEncounter()
2. getEncounterByUuid()	
3. getEncounters()
4. getEncountersByPatientId()
5. getEncountersByPatient()
6. getEncountersByVisit()
7. getEncountersNotAssignedToAnyVisit()
8. getEncountersByVisitsAndPatient()
9. getAllEncounter()
Ticket : https://issues.openmrs.org/browse/LBAC-16

LBAC-16 Added implementation to restrict the encounters of the patients from other locations

---

api/src/main/java/org/openmrs/module/locationbasedaccess/LocationUtils.java
api/src/main/java/org/openmrs/module/locationbasedaccess/PersonSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/UserSearchAdviser.java
omod/src/main/resources/config.xml

- Added the restrictions to these following methods from the UserService class which is directly getting the User object from the DAO.    It can restrict by the locations while directly accessing the users for some other use cases.
1. getUsers()
2. getAllUsers()
3. getUser()
4. getUserByUuid()
5. getUserByUsername()
6. getUserByName()
7. getUsersByPerson()
- Added a method to restrict person object of the users since we haven't assigned the person attribute for those persons belongs to the users.
Ticket : https://issues.openmrs.org/browse/LBAC-15

LBAC-15 Added restrictions to the UserService methods to restrict them by the location

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/PatientSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/PersonSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/UserSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/utils/LocationUtils.java
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/field/LocationsFragmentController.java
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/AddLocationFragmentController.java
omod/src/main/resources/config.xml

Re-structured the classes in the module to keep the module hierarchy in the usual way
Ticket : https://issues.openmrs.org/browse/LBAC-1

LBAC-1 Changed the module structure based on the classes

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/LocationSearchAdviser.java
omod/src/main/resources/config.xml

OpenMRS Location Services is dealing with the location objects, and it serves the list of locations to the system. Since the user is assigned for a location, System should hide other locations from that user access. This PR contains the implementation to hide other locations for the userView. It follows,
- If not authenticated, then exclude all the get* Methods from the restrictions
- if authenticated,
- add restrictions to getAll* methods.
- exclude the getLocation(interger id), else it will be endless loop between the actual getLocation() caller and our module since we need this method inside our module to get the location information. So user can’t get all locations list, he can only get the accessible location(s) in the list. But the user might able to get the location information …

LBAC-18 Added restrictions for Location service get methods

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/PatientSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/utils/LocationUtils.java

We implemented the LBAC for working tightly with the sessionLocationId. So it failed to work for the user through the REST service since that user will not have the sessionLocationId. So We need to give the priority to,
- First - Get the assigned location from user property (Need update)
- Second - Get the assigned location from session location (already implemented)
Ticekt : https://issues.openmrs.org/browse/LBAC-14

LBAC-14 Added fix to check for the user property before session id for Person Restrictions

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/UserSearchAdviser.java

We implemented the LBAC for working tightly with the sessionLocationId. So it failed to work for the user through the REST service since that user will not have the sessionLocationId. So We need to give the priority to,
- First - Get the assigned location from user property (Need update)
- Second - Get the assigned location from session location (already implemented)
Ticekt : https://issues.openmrs.org/browse/LBAC-15

LBAC-15 Added fix to check for the user property before session id for Users Restrictions

---

api/src/main/java/org/openmrs/module/locationbasedaccess/utils/LocationUtils.java

There was a minor issue occurred in the getUserAccessibleLocationUuid method. It should be quickly fixed to avoid the find patients issues.

Added minor fix in the getUserAccessibleLocationUuid method

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/LocationSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/PersonSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/UserSearchAdviser.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/EncounterServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/LocationServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/PersonServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/UserServiceInterceptorAdvice.java

Migrated the private Advice classes to the public classes which can be easily used by other methods (eg  : from unit testing methods) and the class name is changed according to the content of the class (Method Interceptor implementation). This PR contains the changes for, 
1. EncounterSearchAdviser
2. LocationSearchAdviser
3. UserSearchAdviser
4. PersonSearchAdviser
Ticket : https://issues.openmrs.org/browse/LBAC-21

LBAC21 Migrated all the private MethodInterceptor classes to public classes

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/PersonServiceInterceptorAdvice.java

When users calling  getSimilarPeople or other added methods, it calls the PersonServiceInterceptorAdvice. Inside the PersonServiceInterceptorAdvice, it calls getPersonAttributeTypeByUuid to get personAttributeType. Unfortunately, it makes calls like a loop and causes stackoverflowerror. 
So an exception for getPersonAttributeTypeByUuid() method  added in the PersonServiceInterceptorAdvice
Issue : https://issues.openmrs.org/browse/LBAC-27

Added exception for getPersonAttributeTypeByUuid in PersonServiceInterceptorAdvice

---

api/src/test/java/org/openmrs/module/locationbasedaccess/aop/common/AOPContextSensitiveTest.java
api/src/test/java/org/openmrs/module/locationbasedaccess/aop/common/TestWithAOP.java

I've modified `AOPContextSensitiveTest` and `TestWithAOP` to allow to use `MethodInterceptor`s instantiated by the user (to support the use of interceptors not having 0-arg ctr).
Currently to use an interceptor in the test suite the only way to use it is by passing the class of the interceptor using `setInterceptor(Class<? extends MethodInterceptor>)` method. This class is later instantiated with `getClassInstance()` method which creates a new object like `new` keyword was used with 0-arg constructor.
Changes introduced with this PR will allow the developer to pass an explicitly constructed interceptor to the context, so the use of different constructors will be allowed. While most of the interceptors have 0-arg ctors by default, `LocationServiceInterceptorAdvice` must be instantiated …

LBAC-26: Added support for testing MethodInterceptors having other ctors than 0-arg

---

api/src/test/java/org/openmrs/module/locationbasedaccess/aop/LocationSearchAdviserTest.java
api/src/test/resources/include/LocationTestData.xml

I've added `LocationSearchAdviserTest` with tests for every method of `LocationService` affected by `LocationSearchAdviser` - it's also a good base for writing additional tests, with some generic methods included. It also includes a test dataset for this test suite.
**All new and existing tests passed.** 
https://issues.openmrs.org/browse/LBAC-23
GCI task instance: https://codein.withgoogle.com/dashboard/task-instances/6038365762748416/

LBAC-23: Added tests for LocationSearchAdviser class

---

api/src/test/java/org/openmrs/module/locationbasedaccess/aop/EncounterSearchAdviserTest.java

Fixed occurences of improperly used `assertNotNull` method. More info inside the ticket below. :)
see https://issues.openmrs.org/browse/LBAC-30

LBAC-30: Fixed wrong use of assertNotNull in EncounterSearchAdviserTest

---

api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/EncounterServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/LocationServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/PatientServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/PersonServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/aop/interceptor/UserServiceInterceptorAdvice.java
api/src/main/java/org/openmrs/module/locationbasedaccess/utils/LocationUtils.java
api/src/test/java/org/openmrs/module/locationbasedaccess/aop/LocationUtilsTest.java
omod/pom.xml
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/AddLocationFragmentController.java
omod/src/main/java/org/openmrs/module/locationbasedaccess/fragment/controller/manageAccount/ViewUserLocationFragmentController.java
omod/src/main/webapp/fragments/manageAccount/addLocation.gsp
omod/src/main/webapp/fragments/manageAccount/viewUserLocation.gsp
pom.xml

- Made UI changes for the user to select a list of Locations.
- Locations are stored as userproperty with location UUID's concatenated.
- Made changes in Utils and in all `ServiceInterceptorAdvice` to remove those objects which do not belong to User's Location List. 
see https://issues.openmrs.org/browse/LBAC-33

LBAC-33 :Add one or more access locations to a user
